### PR TITLE
mirror-nixos-branch: omit VirtualBox OVAs from channels

### PR DESCRIPTION
**Pull request by emilazy**
See https://github.com/NixOS/nixpkgs/pull/352603.

### CODE REVIEW

**Review by vcunat — APPROVED** [review]
Looks good.  I tested the regexp on the few current cases, too.

But I have no idea about the OVA's usefulness (!)

**Comment by mweinelt** [comment]
Looks like we're going another route, shipping the pre-assembled BIOS.

**Comment by emilazy** [comment]
I still think we should probably do this, since VirtualBox is kind of a mess and I don’t think it should block the channel given the limited usefulness of the OVA (we explicitly have a warning on the homepage that it is just a demo, for which the ISO works perfectly well).

**Comment by emilazy** [comment]
Undrafting per the outcome of my discussion with a VirtualBox maintainer as summarized in https://github.com/NixOS/nixpkgs/pull/352603; I think we should do this.

**Review by mweinelt — APPROVED** [review]

**Pull request merged**
