### PR TITLE
Copy aarch64-linux ISO images unconditionally

### PR DESCRIPTION
**Pull request by mweinelt**
This is a draft and related to the changes made to release-combined and release-small in https://github.com/NixOS/nixpkgs/pull/193600. This is also a prerequisite for https://github.com/NixOS/nixos-homepage/issues/747.

### CODE REVIEW

**Comment by samueldr** [comment]
Before adding too much complexity to this script, we should probably think about implementing it in a way where it consumes data provided by the channel.

See for a once working demo: https://github.com/NixOS/nixos-channel-scripts/pull/25#issuecomment-521511375

**Comment by mweinelt** [comment]
That does indeed sound like the superior approach. We could start by adding the manifest to the release jobs and go from there.

**Review by dasJ — APPROVED** [review]

**Comment by mweinelt** [comment]
Looks like everything is here. Can someone merge?

- https://hydra.nixos.org/job/nixos/trunk-combined/nixos.iso_gnome.aarch64-linux
- https://hydra.nixos.org/job/nixos/trunk-combined/nixos.iso_plasma5.aarch64-linux
- https://hydra.nixos.org/job/nixos/trunk-combined/nixos.iso_minimal.aarch64-linux
- https://hydra.nixos.org/job/nixos/unstable-small/nixos.iso_minimal.aarch64-linux

**Comment by vcunat** [comment]
I haven't done a proper review of this, but won't it break with current `nixos-22.05*` channels?

**Comment by mweinelt** [comment]
Oh, shoot. That's why I left it as a draft in the first place and then I forgot. Thanks for the pointer.

**Pull request merged**
