### PR TITLE
Extend file index

### PR DESCRIPTION
**Pull request by joelmo**
With this a tool can be created to find missing dependencies easier and make packaging process easier. Now this will index .so files but can be extended in the future to index perl and python packages.

I renamed the db file to index.sqlite so the program command-not-found needs a change too.

### CODE REVIEW

**Comment by domenkozar** [comment]
This is extremely useful as I want to automate `patchelf` by scanning files and figuring out what package from Nix to use. I might be possible to get automatic patchelf out of this change ;)

**Comment by domenkozar** [comment]
@joelmo I wouldn't rename the db, it's going to be eaiser to merge.

**Comment by edolstra** [comment]
Hm, not sure if we want to turn `programs.sqlite` into a sort of global `locate` database, because it will be massive. Rather than distribute such a database as part of the channel, it might be an idea to have a web service on `nixos.org` to answer file lookup queries (and then `command-not-found` could use that service as well).

**Comment by joelmo** [comment]
When I indexed my store I got a db of size 848K. I guess a full index easily could go to 300MB some day. So I understand that this can't be distributed to channel updates. A web service sounds good, maybe where clients have cache. But then this feature should be moved to hydra?

**Comment by joelmo** [comment]
Is it possible we generate a separate db for just the libs that will not be part of the channel but one that people can download somewhere?

**Comment by domenkozar** [comment]
Sure, we could have a website to offer such things.

Note that the scripts has been rewritten in C++ to handle S3 cached packages so this PR will never apply cleanly. https://github.com/NixOS/nixos-channel-scripts/commit/ab086b22efb4865c2b9180bff1d17aa46f64da70

I'd happily have a website that has the index of all files, but this should be done as a separate project.

**Comment by joelmo** [comment]
Will that be ok as a separate project, then you have to download all packages now and then. Would it be ok to implement this as some optional service in hydra?

**Comment by domenkozar** [comment]
Hydra could generate such index, but with distributed builds this won't be easy to implement.

**Pull request closed without merging**
