### PR TITLE
Add netboot files

### LINKED ISSUE #6: NixOS channels: copy also PXE boot
Once https://github.com/NixOS/nixpkgs/pull/14740 is merged, it would be nice to also copy `nix-build -A netboot nixos/release.nix` result to the channel so NixOS can be booted using (i)PXE.

### PR DESCRIPTION
**Pull request by lheckemann**
Allows adding nixos support to netboot.xyz (antonym/netboot.xyz#37). NOT TESTED. Depends on nixos/nixpkgs#43805. Fixes #6

Also fixes building the scripts on the side.

cc @fpletz @domenkozar @nshalman @matthewbauer who have expressed interest in netboot.xyz support

### CODE REVIEW

**Comment by edolstra** [comment]
That's not a problem as long as the derivation emits a `hydra-build-products` file (similar to the ISO image jobs).

**Comment by lheckemann** [comment]
Yes, I realised this earlier. However, since A) these derivations aren't actually hydra jobs and B) the netboot files are symlinks (nixos/hydra#580), this doesn't work yet.

**Comment by lheckemann** [comment]
Fixed! Things to note:

 - I made AWS upload optional, so that I could test the script to some extent myself
 - I reworked downloadFile to support multiple build products
 - Netboot is ignored if downloading it fails, because not all current channels currently contain nixos/nixpkgs#44089

**Comment by lheckemann** [comment]
> How will netboot.xyz find these files?

After this, they should be available at https://nixos.org/channels/nixos-{18.03,unstable}/netboot.ipxe.

> What filename are they uploaded to? I gather it's {netboot.ipxe,initrd,bzImage}. In that case they should really be put in a subdirectory since having files names initrd or bzImage is not very informative.

That makes sense, I can try doing that.

> I gather from antonym/netboot.xyz#37 that netboot.xyz can use ISOs directly. [snip] Why can't we do that?

It's unable to find the root filesystem, for reasons similar to boot failures caused by incorrect USB stick creation.

> much preferred to adding yet another big image to our release process

These files are already built by hydra, does including them on the channel page make a big difference?

> Does it contain the entire Nix store or something? Doesn't that require the entire initrd to be decompressed into memory?

Yes and no respectively. It contains the entire nix store as a squashfs (much like the CD image), which is mounted and decompressed on the fly.

> Aside: the ideal netboot would be to have a minimal initrd that mounts cache.nixos.org on /nix/store (via NixOS/nix@a9cbd67) and boots the system closure from there.

That is awesome! Orthogonal to this change, but it should allow making the initrd a bit smaller in future versions.

**Comment by Mic92** [comment]
ping @lheckemann

**Comment by Mic92** [comment]
zram and zstd might help: https://github.com/NixOS/nixpkgs/pull/52991

**Comment by danbst** [comment]
@Mic92 current zramSwap module isn't designed to be started in stage1. Also, if that squashfs @lheckemann mentions is already compressed, then it can't be compressed more, and thus no extra memory gain.

**Comment by Mic92** [comment]
This snippet would download the iso in the initrd: http://paste.r/hYJJeT2X/+inline

**Comment by JohnAZoidberg** [comment]
Do the images that `netboox.xyz` uses work?
Is it enough to have netbook fetch them from Hydra? Wouldn't it be nice to have it in the channel?

That doesn't finish for me, even after a few minutes:
```
$ wget https://hydra.nixos.org/job/nixos/trunk-combined/nixos.netboot.x86_64-linux/latest-finished/download/netboot.ipxe
--2019-07-04 23:04:11--  https://hydra.nixos.org/job/nixos/trunk-combined/nixos.netboot.x86_64-linux/latest-finished/download/netboot.ipxe
Resolving hydra.nixos.org (hydra.nixos.org)... 46.4.67.10, 2a01:4f8:140:248f::
Connecting to hydra.nixos.org (hydra.nixos.org)|46.4.67.10|:443... connected.
HTTP request sent, awaiting response... 
```

**Comment by Lassulus** [comment]
I just tested it inside a qemu VM, the unstable channel image works, even though the wget also does nothing for me.
Would still be nice to have the netboot stuff in the channel to have it on a faster server. But as long as it works I'm happy

**Pull request closed without merging**
