### PR TITLE
mirror-nixos-branch: Ignore some download errors

### PR DESCRIPTION
**Pull request by dasJ**
This code is not really tested but at least it parses

### CODE REVIEW

**Comment by samueldr** [comment]
We're missing the rationale here.

Why is this needed?

**Comment by dasJ** [comment]
I don't know exactly but you can follow Grahams description here: https://matrix.to/#/!RROtHmAaQIkiJzJZZE:nixos.org/$bDX8VpIshP0GaPj7FSJaviURrmSDXOKMy9f2uwc4CKs?via=nixos.org&via=matrix.org&via=helsinki-systems.de

**Comment by samueldr** [comment]
This would be the wrong approach AFAICT, as this would advance channels when it shouldn't (from outputs not being present).

It should instead match on `channelName`, looking for the platform, I suppose.

**Comment by dasJ** [comment]
Replaced by #52

**Pull request closed without merging**
