### PR TITLE
Ship Plasma 6 ISOs

### PR DESCRIPTION
**Pull request by K900**
NixOS side: https://github.com/NixOS/nixpkgs/pull/313167

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Review by mweinelt — CHANGES_REQUESTED** [review]
Before we merge this there should be an eval that has the ISO or downloadFile will fail.

**Comment by vcunat** [comment]
There will be at least a few hours of time between the merge and eval finishing.

**Comment by vcunat** [comment]
Oh, merge happened and no eval is pending, so... I'd say we can deploy.  (unless it's buggy)

**Comment by K900** [comment]
I just merged the nixpkgs side, so we can get an eval with the staging merge.

**Review by vcunat — COMMENTED** [review]
Deployed and `trunk-combined` evaluating 🤞🏽

**Comment by vcunat** [comment]
`nixos-unstable` channel updated with this.  I see no issue at a glance.  Anyone else objects?

**Comment by mweinelt** [comment]
I think we are good.

image

https://releases.nixos.org/nixos/unstable/nixos-24.05pre629267.3eaeaeb6b1e0

**Comment by vcunat** [comment]
The only complication is that for integration of this into the infra repo we'll need to update nixpkgs also on other machines.

**Comment by mweinelt** [comment]
Queued an update for the homepage.

https://github.com/NixOS/nixos-homepage/pull/1436

**Pull request merged**
