### PR TITLE
rename iso_graphical to iso_plasma5

### PR DESCRIPTION
**Pull request by worldofpeace**
Coordinate with NixOS/nixpkgs#66640

### CODE REVIEW

**Comment by samueldr** [comment]
How will it work with "mixed channels", e.g. the span up to the EOL of 19.03? We'll have updates for both 19.03 and 19.09/unstable going on, with a different sent of images being generated.

**Comment by worldofpeace** [comment]
Perhaps we backport all of the renames?

**Comment by grahamc** [comment]
We should probably not backport renames, as that is a pretty big change which somebody might have built against.

I propose we put a blocking 19.09 issue in nixpkgs saying merge these two PRs at release time.

**Comment by grahamc** [comment]
Hrm. Using `$releaseName` is for sure the right thing to do, as otherwise channel updates will fail for all prior branches.

**Comment by worldofpeace** [comment]
Yep, and I think the script will need this in the future if the `gnome3` iso gets added.
As `19.09` and `unstable` will have this new iso but all prior releases won't.

**Comment by samueldr** [comment]
(light bikeshedding warning) It would be great if the release could define artifacts, and that definition be used to generate the page, instead of making it in the script. This would ensure future additions (hint: aarch64 releases?) to be done without having to hack around in the publishing script.

**Comment by worldofpeace** [comment]
https://github.com/NixOS/nixos-channel-scripts/pull/25/commits/e72e5c7cdde40999d8a6c303835861bfbd1388d2 maybe does the things?
(insert nonbinary shrug emoji)

**Comment by samueldr** [comment]
Here's my 1:1 replica of the bikeshed, with the colour applied to it

 * https://github.com/samueldr/nixos-channel-scripts/commit/e1c6c15a2b747b8c2f8458556fbe2430c2139f1e
 * https://github.com/NixOS/nixpkgs/compare/master...samueldr:wip/release-scripts

The main idea being that there's a job added to the channels, listing job names that will be published by the release script. (Except for pre-19.09 releases, where it uses the fixed manifest equivalent.)

Here are things I don't like from my first draft:

 * Jobs are listed in an unordered manner
 * Jobs are mapped in a hash, the key being the hydra job name, the value being either null (ugh) or the expected filename

And the things I think might ruffle some feathers:

 * Special job
 * Job name starting with `_`

I am not attached to the implementation, though I think the concept is sound. Let's make each released channels describe their own "publishables".

* * *

@edolstra your input would be appreciated. I think this is generally the right direction, but it would be nice to have some advice, and your opinion, about the best way to handle the concept. Thanks.

**Pull request merged**
