### PR TITLE
Fixes channel going back in time due to incomplete change.

### PR DESCRIPTION
**Pull request by samueldr**
The change in d3d33d5b2518e4e6516b6f31270b406937c48ca2 changed how the
locally saved channel information was saved on the local machine.

 * https://github.com/NixOS/nixos-channel-scripts/commit/d3d33d5b2518e4e6516b6f31270b406937c48ca2#diff-682bf482f6dd273f1c3c49afd99b4660R192

The changeset did *not* change the guard clause, which now made it act
like this:

 1. Try readlink on the file
 2. (bail as it's undefined)

The new behaviour is as more or less expected:

 1. Reads the file if available
 2. Split the URL components
 3. Keep the last bit

This can give us an empty string, which will compare to `-1` thus
fulfilling the need.

* * *

I'd like to add these big disclaimers:

 1. The change as it is has not been tested fully integrated, due to the lack of a sandbox to play around replicating how the server works.
 1.  I am not a perl developer, thus my implementation may lack the fine polish of a well-versed perl developer.

The code was as thoroughly tested as possible through this naïve script, which mostly replicates whatever is required.

 * https://gist.github.com/samueldr/f34d8684d68252df95667df60ccd7b7d

This file *is* a giant hack :).

### CODE REVIEW

**Comment by vcunat** [comment]
Hmm, right now we offer `18.09-beta-740-g6cbd1ec4b04` &ndash; commit pushed on Oct 3.  That's suspicious to me.

**Comment by vcunat** [comment]
By kicking Hydra I managed `18.09.783.299814b385d` now.  From a quick thought I suspect if changing the name (`-beta`) could've broken the ordering or something.

**Comment by andir** [comment]
Same is happening with 18.03. It bounced back to 20th of September. No renaming was done there as far as I can tell.

**Comment by domenkozar** [comment]
Could be this change wasn't deployed yet :)

**Comment by vcunat** [comment]
@edolstra: is it easy to check whether this has been deployed?  (Or at least try re-deploy blindly, but it would be nice to know if this PR didn't help.)

**Comment by edolstra** [comment]
Looks like it's *not* deployed...

**Comment by edolstra** [comment]
Now it is.

**Pull request merged**
